---
# This playbook deploys the whole dev stack for a workstation .

- name: apply common configuration to all nodes
  hosts: all
  become: true

  roles:
    - common
  environment:
    ANSIBLE_VAULT_PASSWORD_FILE="dotfiles/.vault_pass"
