- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_distribution

- name: Remove software
  ansible.builtin.dnf:
    name: 
      - elisa
      - transmission
    state: absent
    autoremove: yes

- name: Install software
  ansible.builtin.dnf:
    name: 
      - akregator
      - bleachbit
      - chromium
      - htop
      - gimp
      - iperf3
      - nmap
      - okular
      - qbittorrent
      - rsync
      - screen
      - sshuttle
      - terminator
      - thunderbird
      - tmux
      - vlc
      - wget
      - wireshark
    state: latest
    update_cache: true
