#Install vscodium
    - name: Add codium repo
      ansible.builtin.yum_repository:
        name: codium
        description: VS Codium repo
        file: codium
        baseurl: https://download.vscodium.com/rpms/
        gpgcheck: yes
        gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
    - name: Install codium
      ansible.builtin.dnf:
        name: 'codium'
        state: present

