#@todo - set up nfs to work with vagrant - nfs3vs4 tcp vs udp
#Set up NFS
 
    - name: Install NFS server packages
      dnf:
        name:
          - nfs-utils
        state: present

    - name: Create the NFS export directory
      file:
        path: /var/nfs/vagrant  
        state: directory
        mode: 0755

    - name: Configure the NFS export
      lineinfile:
        path: /etc/exports
        line: "/var/nfs/vagrant *(rw,sync,no_subtree_check,fsid=0,proto=tcp,vers=3)" 
        create: yes

    - name: Ensure NFS server supports TCP (if needed)
      lineinfile:
        path: /etc/sysconfig/nfs  # Path may vary on some distributions
        regexp: '^RPCNFSDOPTS='
        line: 'RPCNFSDOPTS="-N 3 -N 2"' 
        create: yes

    - name: Enable and start the NFS services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - nfs-server
        - rpcbind

<<<<<<< HEAD:roles/workstation/tasks/nfs.yml
    
    - name: Configure firewall for NFS (if firewalld is active) 
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
       - nfs
       - rpc-bind
       - mountd
      when: ansible_facts.services['firewalld.service'].state == 'running'

      
=======
    - name: Stop service httpd, if started
      ansible.builtin.service:
        name: firewalld
        state: stopped
        
   # - name: Configure firewall for NFS (if firewalld is active) 
   #   firewalld:
   #     service: "{{ item }}"
    #    permanent: yes
    #    state: enabled
    #    immediate: yes
    #  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 5  
    #  with_items:
    #    - nfs
    #    - rpc-bind
    #    - mountd
>>>>>>> ca73e67ea5ca7b99d0189396a742449aaf98fe89:roles/common/tasks/nfs.yml
