    #Install Vagrant
    - name: Add Hashicorp repo
      ansible.builtin.yum_repository:
        name: hashicorp
        description: Hashicorp repo
        file: hashicorp
        baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://rpm.releases.hashicorp.com/gpg
    - name: Install vagrant
      ansible.builtin.dnf:
        name: 'vagrant'
        state: present
    #Install Vagrant Plugins
    - name: add vagrant-libvirt plugin
      ansible.builtin.command: vagrant plugin install vagrant-libvirt
    - name: add vagrant-hostmanager plugin
      ansible.builtin.command: vagrant plugin install vagrant-hostmanager
    - name: add vagrant-mutate plugin
      ansible.builtin.command: vagrant plugin install vagrant-mutate
    - name: add vagrant-scp plugin
      ansible.builtin.command: vagrant plugin install vagrant-scp