- name: Import prerequisite tasks
  ansible.builtin.import_tasks: prerequisites.yml

- name: Install base applications
  ansible.builtin.import_tasks: base_apps.yml


- name: Install vscodium
  ansible.builtin.import_tasks: codium.yml

