- name: Import prerequisite tasks
  ansible.builtin.import_tasks: prerequisites.yml

- name: start firewalld
  ansible.builtin.import_tasks: firewalld.yml

- name: Install base applications
  ansible.builtin.import_tasks: base_apps.yml
  
- name: Import vagrant install
  ansible.builtin.import_tasks: vagrant.yml

- name: Install nfs
  ansible.builtin.import_tasks: nfs.yml

- name: Import vpn setup
  ansible.builtin.import_tasks: vpn.yml

# Broken
#- name: Import config files
  #ansible.builtin.import_tasks: dotfiles.yml

- name: Install vscodium
  ansible.builtin.import_tasks: codium.yml

<<<<<<< HEAD
# Broken
- name: Install Slack
  ansible.builtin.import_tasks: slack.yml

#- name: Print all available facts
#  ansible.builtin.debug:
#    var: ansible_distribution
=======

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_distribution
>>>>>>> be4bca2e55ddabf2c5bfe659a9dcc421effa7194
