#Prerequisites installation
  
  - name: SELinux
    ansible.posix.selinux:
     policy: targeted
     state: permissive

  - name: Enable the CodeReady Linux Builder repository
    become: true
    ansible.builtin.command: dnf config-manager --enable crb
    args:
      creates: /etc/yum.repos.d/rocky-crb.repo
    when:
     - ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution'] == 'RedHat'
  - name: add epel
    ansible.builtin.dnf:
      name: epel-release
      state: present
    when:
    - ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution'] == 'RedHat'
  - name: Install rpmfusion free
    ansible.builtin.dnf:
      name: 'https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm'
      disable_gpg_check: true
      state: present
  - name: Install rpmfusion nonfree
    ansible.builtin.dnf:
      name: 'https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm'
      disable_gpg_check: true
      state: present
>>>>>>> ca73e67ea5ca7b99d0189396a742449aaf98fe89
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  
#Development tools
  - name: Install Development Tools
    ansible.builtin.dnf:
      name: '@Development Tools'
      state: present
  - name: Install libvirt-devel (needed for vagrant-libvirt plugin)
    ansible.builtin.dnf:
      name: libvirt-devel
      state: present

#Add user to groups
  - name: Add the user 'wdundore' with a bash shell, appending the group 'libvirt' and 'vagrant' to the user's groups
    ansible.builtin.user:
      name: wdundore
      shell: /bin/bash
      groups: libvirt
      append: yes

  - name: Copy a new sudoers file into place, after passing validation with visudo
    ansible.builtin.template:
      src: 10_wdundore.j2
      dest: /etc/sudoers.d/10_wdundore
      validate: /usr/sbin/visudo -cf %s
