#Install Mullvad vpn
    - name: Add Mullvad repo
      ansible.builtin.yum_repository:
        name: mullvad
        description: Mullvad VPN
        file: mullvad
        baseurl: https://repository.mullvad.net/rpm/stable/$basearch
        gpgcheck: yes
        gpgkey: https://repository.mullvad.net/rpm/mullvad-keyring.asc
    - name: Install Mullvad VPN
      ansible.builtin.dnf:
        name: 'mullvad-vpn'
        state: present